---
- hosts: webservers
  become: true
  become_user: root
  tasks:
    - name: install package
      yum: name=docker state=present
    - name: start the service
      service: name=docker state=started
